version: '3'
services:
  rtsp2rsas:
    restart: always
    container_name: rtsp2rsas
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      RTSP_URL: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
      ICECAST_URL: x.x.x.x
      ICECAST_PORT: xxxx
      ICECAST_USERNAME: stream-username
      ICECAST_PASSWORD: stream-password
      ICECAST_MOUNTPOINT: mountpoint
